// action types

// SIGN UP ACTIONS
export const USER_SIGNED_UP = 'USER_SIGNED_UP';
export const WELCOME_SUCCESS = 'WELCOME_SUCCESS';
export const START_NEW_TARGET = 'START_NEW_TARGET';
export const END_NEW_TARGET = 'END_NEW_TARGET';
export const UPDATE_RADIUS = 'UPDATE_RADIUS';
export const CREATE_TARGET_SUCCESS = 'CREATE_TARGET_SUCCESS';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const API_ERROR = 'API_ERROR';
export const GET_TARGETS_SUCCESS = 'GET_TARGETS_SUCCESS';
