// action types

// SIGN UP ACTIONS
export const USER_SIGNED_UP = 'USER_SIGNED_UP';
export const WELCOME_SUCCESS = 'WELCOME_SUCCESS';
export const START_NEW_TARGET = 'START_NEW_TARGET';
export const END_NEW_TARGET = 'END_NEW_TARGET';
export const UPDATE_RADIUS = 'UPDATE_RADIUS';
export const CREATE_TARGET_SUCCESS = 'CREATE_TARGET_SUCCESS';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GENERIC_ERROR = 'GENERIC_ERROR';
export const GET_TARGETS_SUCCESS = 'GET_TARGETS_SUCCESS';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SELECT_TARGET = 'SELECT_TARGET';
export const DELETE_TARGET = 'DELETE_TARGET';
export const END_SELECT_TARGET = 'END_SELECT_TARGET';
export const DELETE_TARGET_SUCCESS = 'DELETE_TARGET_SUCCESS';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';
